---
#--------------------------------------------------
# Install Tower
#--------------------------------------------------

- name: Create temp tower install dir
  become: yes
  file:
    path: /tmp/tower/
    state: directory
 
- name: Download and Unarchive Tower Package
  become: yes
  unarchive: 
    src: http://releases.ansible.com/ansible-tower/setup/ansible-tower-setup-latest.tar.gz
    dest: /tmp/tower
    remote_src: yes
    creates: /tmp/tower/ansible-tower-setup/

- name: Rename dir to ansible-tower-setup
  become: yes
  shell: mv ansible-tower-setup-*/ ansible-tower-setup chdir=/tmp/tower
  args: 
    creates: /tmp/tower/ansible-tower-setup/setup.sh

- name: Template over Ansible Inventory to setup
  become: yes
  template: 
    dest: /tmp/tower/ansible-tower-setup/inventory
    src: inventory.j2

- name: Install Tower
  become: yes
  become_user: root
  command: ./setup.sh chdir=/tmp/tower/ansible-tower-setup/  
  args:
    creates: /usr/bin/ansible-tower-service
  async: 1200
  poll: 2

#-------------------------------------------------------------------------------------------
# Request a license from https://www.ansible.com/workshop-license and add it to the files dir
#--------------------------------------------------------------------------------------------
- name: Add Ansible Tower License
  become: yes
  become_user: root
  copy: src=license dest=/etc/tower/license

