---

#--------------------------------------------------
# Install tower, copy apache exercises, copy tower backup file for Tower exercises  
#--------------------------------------------------

- import_tasks: apache_exercises.yml 
- import_tasks: install_tower.yml
- import_tasks: setup_tower.yml
- import_tasks: oscap_exercise.yml 

#--------------------------------------------------
# Remove install dir 
#--------------------------------------------------

- name: Remove the temp tower install dir
  become: yes
  file:
    path: /tmp/tower/
    state: absent

